$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME=Catppuccin-Dark-Frappe
$CURSOR_THEME=catppuccin-frappe-dark-cursors
$COLOR_SCHEME=prefer-light

general {
    gaps_in = 2
    gaps_out = 7
    border_size = 2
    col.active_border = rgba(D75BC1ff) rgba(EB9592ff) 45deg
    col.inactive_border = rgba(C49AE5ff) rgba(C89DE6ff) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(DC7BC1ff) rgba(EB9592ff) 45deg
    col.border_inactive = rgba(C49AE5cc) rgba(C89DE6cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}

decoration {
    rounding = 10
    active_opacity = 0.95
    inactive_opacity = 0.90

    shadow {
    enabled = true
    # Hyprland 0.55+ always uses the former ignore_window=true behavior.
    render_power = 2
    color = 0x80ffffff
    range = 14
    offset = 0 0
    }

    blur {
        enabled = yes
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
layerrule = blurpopups,waybar
